### ISSUE TITLE
Getting null body in the SaveMediaResponse while calling bynderApi.saveMedia

### ISSUE THREAD

**Issue by mshajahangit** [Bynder/bynder-java-sdk#14]
I am trying to integrate the Bynder Java sdk with my project, the major task is to upload the files, i tried sample APIs like getTags, getMediaList, i am able to print all the details as per the environment.

But when i am trying to upload a file i get a null in the SaveMediaResponse.body();
I also see the flag hasFinishedSuccessfully is true, Seems everything gone smooth when trying to upload in S3, only fails in the Bynder saveMediaapi response.

Since the body is null the code fails in emitter.onNext(saveMediaResponse.body()
[saveUploadedMedia method in FileUploader class]

Request you to please guide me further to upload the image file.

**Comment by mshajahangit** [comment]
For more insight printing the details:
uploadQuery.getFilepath() D:\Bynder\image.jpg
uploadRequest  pluploads/b5d47915-f145-4e81-9e38-3a68378a451f/D-Bynder-image.jpg
importId 6D7EB478-E20B-4661-B10A3B0AF95843B9
hasFinishedSuccessfully true
uploadQuery.getMediaId() TTTTTTTT
Before Calling Save API
params {importId=6D7EB478-E20B-4661-B10A3B0AF95843B9, audit=true, id=TTTTTTTT}
body=null success=false [saveMediaObs = saveMedia(
                    new SaveMediaQuery(importId).setMediaId(uploadQuery.getMediaId())
                        .setAudit(uploadQuery.isAudit()));
                System.out.println("Else Done"+ saveMediaObs.subscribe(s -> System.out.println("body="+s.body()+" success="+s.isSuccessful())));]

**Comment by danielsequeira** [comment]
hey @mshajahangit,

are you getting any exception or error message regarding this?

**Comment by mshajahangit** [comment]
[exception.txt](https://github.com/Bynder/bynder-java-sdk/files/2904826/exception.txt)

**Comment by danielsequeira** [comment]
Do you reference the sdk or do you have it cloned? And if so did you change anything in the source code? I was looking through the exception.txt file and some of the lines referenced from the FileUploader class are comment lines, what doesn't make a lot of sense.

Also what exactly arguments do you pass in the UploadQuery when calling the uploadFile method? I can't really understand from your previous messages.

**Comment by mshajahangit** [comment]
source code changes done, only for debugging added some system outs to check what is printed.

  UploadQuery uploadFile = new UploadQuery("D:\\Bynder\\image.jpg", "1234124341234");
		        uploadFile.setMediaId("TTTTTTTT");
		        uploadFile.setAudit(true);
		        Observable<SaveMediaResponse> uploadStatus= assetBankService.uploadFile(uploadFile);
		        System.out.println("uploadStatus =  " + uploadStatus);
		        uploadStatus.subscribe(u -> System.out.println(u.getSuccess()));

**Comment by mshajahangit** [comment]
Attaching fileuploader what is used, just added some sysouts to know what went wrong, uploading as is file
[FileUploader.txt](https://github.com/Bynder/bynder-java-sdk/files/2905928/FileUploader.txt)

**Comment by danielsequeira** [comment]
so you are actually trying to upload a new version for the media with id TTTTTTTT ? right?

**Comment by mshajahangit** [comment]
nope that file has not yet uploaded even once.  I am just trying to see if upload gets success so tried with sample file, but failed

**Comment by mshajahangit** [comment]
I also tried to upload without sending the mdeia id TTTTTTTT, still got same response

**Comment by danielsequeira** [comment]
ok, I will try to replicate it and see what the issue might be.

one more question, how are you initialising the SDK? Which arguments are you passing to the BynderService class?

**Comment by mshajahangit** [comment]
i tried passing the valid media id, where the image already present, i got uploaded successfully.

Then how do i upload a new image, i tried without sending media id, it fails..

ok answer to your questions is

settings = new Settings(new URL("url"), "consumer key",
			            "consumer secret", "Access Token", "Token secret");
bynderService = BynderServiceImpl.create(settings);
		        AssetBankService assetBankService = bynderService.getAssetBankService();

**Comment by danielsequeira** [comment]
in order for me to be able to reproduce it, could you tell me to which Bynder portal url you are uploading to? and which is the brandId that you are using?

**Comment by mshajahangit** [comment]
https://beta.brand.akzonobel.com

Brand id is mandatory ?? since i see to upload media ID and audit parameter if i send is enough ? please confirm if need to upload new image what all the parameter do i need to pass

**Comment by danielsequeira** [comment]
yes, brandId is mandatory, as you can see by the UploadQuery constructor definition: https://github.com/Bynder/bynder-java-sdk/blob/master/src/main/java/com/bynder/sdk/query/UploadQuery.java#L32

A media always need to have a brand

**Comment by mshajahangit** [comment]
Yeah got it, as i am also passing the id 

 UploadQuery uploadFile = new UploadQuery("D:\\Bynder\\image.jpg", "1234124341234");
		        uploadFile.setMediaId("TTTTTTTT");
		        uploadFile.setAudit(true);
		        Observable<UploadProgress> uploadStatus= assetBankService.uploadFileWithProgress(uploadFile);
		        System.out.println("uploadStatus =  " + uploadStatus);

**Comment by danielsequeira** [comment]
For example to upload the file located in: /user/downloads/image.png, I would do the following:

`Response<List<Brand>> brandListResponse = assetBankService.getBrands().blockingSingle();
List<Brand> brandList = brandListResponse.body();
Brand brand = brandList.get(0);
SaveMediaResponse saveResponse = assetBankService.uploadFile(new UploadQuery("/user/downloads/image.png", brand.getId())).blockingSingle();`

**Comment by danielsequeira** [comment]
We just did some investigation and it seems that you are either passing an invalid brandId or an invalid mediaId.

Just to be clear, are you actually passing the string "1234124341234" as brandId?

**Comment by mshajahangit** [comment]
ok Assume i want to upload a new file or image, what should be the brandid or media id ? can u please guide on this ?

**Comment by mshajahangit** [comment]
After your suggestion i tried this piece of code below still fails.

UploadQuery uploadFile = new UploadQuery("D:\\Bynder\\image.jpg", "7CACD5BB-1BD4-4E44-12345F567FE127B7");
		        uploadFile.setMediaId("52C71234-86B2-4A69-8007FA68BA0B1234");
		        uploadFile.setAudit(true);
		        Observable<UploadProgress> uploadStatus= assetBankService.uploadFileWithProgress(uploadFile);
		        System.out.println("uploadStatus =  " + uploadStatus);

**Comment by danielsequeira** [comment]
Does it fail with the same error? Or is it a different error? Could you share the stacktrace with us?

Also we tried to replicate this in our side but we couldn't do it, it works for us.

**Comment by danielsequeira** [comment]
I just look in the database and the brandId `7CACD5BB-1BD4-4E44-12345F567FE127B7` doesn't exist for the account https://beta.brand.akzonobel.com.

I can see this brandId though: `7CACD5BB-1BD4-4E44-9E600F567FE127B7`

**Comment by danielsequeira** [comment]
and the media id: 52C71234-86B2-4A69-8007FA68BA0B1234 doesn't exist as well.

you will need to use valid and existing ids to make the call work

**Comment by mshajahangit** [comment]
Hi @danielsequeira ,

Seems like i understand some parts now, i see that brandId is associated with the images and 1 brand can have multiple images, correct me if i am wrong.

What is media id here ?

**Comment by danielsequeira** [comment]
Hi @mshajahangit,

Yes that's true, all the media (images, videos, documents, etc.) need to be part of a brand and a brand can have multiple images.
You can get information about the brands of https://beta.brand.akzonobel.com by doing the following call: `List<Brand> brandList = assetBankService.getBrands().blockingSingle().body();`

Media id is the id of any image, video or document that is part of https://beta.brand.akzonobel.com. If you login to https://beta.brand.akzonobel.com and click in "Media Library" you will see all the media that is part of this portal. Then if you click in any of the media displayed there you will be able to see that media id in your browser url, it will look like: https://beta.brand.akzonobel.com/media/?mediaId=00000000-0000-0000-0000000000000000.

Another way to access media ids is to do the following call: `List<Media> mediaList = assetBankService.getMediaList(new MediaQuery()).blockingSingle();.body();`

Anyway to upload a new file to https://beta.brand.akzonobel.com, you don't need a media id, only if you want to upload a new version of an existing media. If you just want to upload a new one, the only thing you need is a filepath and a valid brand id.

Example of uploading a new media to https://beta.brand.akzonobel.com:
`SaveMediaResponse saveResponse = assetBankService.uploadFile(new UploadQuery(filepath, brandId)).blockingSingle();`

Example of uploading a new version for the media with id "mediaId" to https://beta.brand.akzonobel.com:
`SaveMediaResponse saveResponse = assetBankService.uploadFile(new UploadQuery(filepath, brandId).setMediaId(mediaId)).blockingSingle();`

**Comment by mshajahangit** [comment]
Hi @danielsequeira ,

I understand what you are saying, i tried as per suggestion it works, Thanks for the guidance.

1. But the question lies, what if i want to upload a new image with new Brand id, how do i make a new brand id which is not present in the portal https://beta.brand.akzonobel.com, then i upload.
2. I see the Bynder creates version on every image i upload, what if i want to overwrite always, since i do not need the versions.

Please guide me.

**Comment by danielsequeira** [comment]
Hi @mshajahangit,

1. It is not possible to create a new brand through the API and therefore through this SDK. The only way to create new brands is through the web application.
2. You only have two options: upload a new image or upload a new version for an existing image. When you upload a new version for an image, this new version also overrides the existing one and becomes the current version of the image.
3. For https://digital.brand.akzonobel.com you can go to Settings -> Taxanomy -> Brands. Or do the SDK call to get brands for this portal.
