### ISSUE TITLE
Asset downloaded with wrong filename

### ISSUE THREAD

**Issue by DenisKusakin** [Bynder/bynder-java-sdk#16]
Hi,
I'm trying to do the following thing

```final BynderService bynderService = BynderServiceImpl.create(new Settings(new URL(revaUrl), consumerKey, consumerSecret, token, tokenSecret));

final UploadQuery uploadQuery = new UploadQuery("D:\\test-images\\reva-upload.jpeg", null)

bynderService.assetBankService.uploadFile(uploadQuery).blockingSingle().mediaId
```

This code creates new asset in bynder, when I try to download it using web interface the file downloaded with the following name: 'D-test-images-reva-upload.jpeg' while I expect to see 'reva-upload.jpeg'

Is it possible to use original filename instead of name generated based on full asset path?

I played a bit with code and as far as I see this happens because `FileUploader.getUploadInformation` passes full file path as filename parameter to init upload request.

Thanks

**Comment by BenMSmith** [comment]
Hi Denis,

The Bynder Java SDK is open source - you should be able to modify the functions you've described as needed to send only the filename sent in the UploadQuery as the filename parameter in the initial upload request rather than the full filepath.

**Comment by DenisKusakin** [comment]
@BenMSmith Thank you for your reply
I just want to clarify, is it intended behavior in sdk or it is a bug and is there any chance it will be fixed?

**Comment by danielsequeira** [comment]
Hey @DenisKusakin, I was looking into the code and we could actually consider this a bug, I think it makes more sense to actually just pass the filename and not the full path to the `FileUploader.getUploadInformation` method.

**Comment by DenisKusakin** [comment]
Hey @danielsequeira , I guess I can create a pull request if you are ok with this

**Comment by danielsequeira** [comment]
Sure, go ahead!

**Comment by DenisKusakin** [comment]
Hey @danielsequeira, thank you for merging my PR, I would really appreciate if you can release new version since I really need this fix

**Comment by danielsequeira** [comment]
Hey @DenisKusakin, yes sure, I'm quite busy now but I will do it today
