### ISSUE TITLE
Retrieving assets with "includeMediaItems"

### ISSUE THREAD

**Issue by onnovandillen** [Bynder/bynder-java-sdk#22]
Hi,

Using the SDK I have been able to request assets using the includeMediaItems=1 parameter. I've done this by creating my own subclass of com.bynder.sdk.query.MediaQuery and adding an @ApiField to that. 

However, the response is missing some information. The media items are deserialized to objects of class com.bynder.sdk.model.MediaItem - this class however doesn't include the API fields "publicURL" and "name".

Attached is a response from the API that I would like to deserialize using the SDK.
Is this possible?

`[
    {
       
        "id": "{id}",
        "description": "",
        "extension": [
            "jpg"
        ],
        "height": 3648,
        "type": "image",
        "orientation": "landscape",
        "watermarked": 0,
        "limited": 0,
        "mediaItems": [
            {
                "publicUrl": null,
                "name": "thumbnail",
                "type": "web"
            },
            {
                "publicUrl": null,
                "name": "small",
                "type": "web"
            },
            {
                "publicUrl": null,
                "name": "medium",
                "type": "web"
            },
            {
                "publicUrl": null,
                "name": "large",
                "type": "web"
            },
            {
                "publicUrl": null,
                "name": "online",
                "type": "web"
            }
        ]
    }
]`

**Comment by WouterToering** [comment]
Hi @onnovandillen,

Like you've noticed already `MediaItem` is missing these fields, which is because it was created for the detail call which has a different output than the asset lists call.

Unfortunately a choice was made to rename `fileName` (from the detail API output) to `name`, which makes it a bit tricky for us to add these fields to the SDK now, since it would break backwards compatibility. Perhaps we should introduce another MediaItem type for this specific call in the future.

Are you able to add these yourself on your end? Just an example of what I've changed locally to get your desired result:

```diff
--- a/src/main/java/com/bynder/sdk/model/MediaItem.java
+++ b/src/main/java/com/bynder/sdk/model/MediaItem.java
@@ -23,7 +23,6 @@ public class MediaItem {
     /**
      * Filename of the media item.
      */
-    @SerializedName(value = "fileName")
     private String name;
     /**
      * Media item type. Possible values are: original, additional, web.
@@ -33,6 +32,10 @@ public class MediaItem {
      * Date created.
      */
     private String dateCreated;
+    /**
+     * Public URL of the media item when available.
+     */
+    private String publicUrl;
     /**
      * Height of the media item.
      */
@@ -78,6 +81,10 @@ public class MediaItem {
         return dateCreated;
     }

+    public String getPublicUrl() {
+        return publicUrl;
+    }
+
     public int getHeight() {
         return height;
     }
```

**Comment by onnovandillen** [comment]
Hi @WouterToering ,

Thanks for your response. In the meantime I have indeed modified the source in a similar manner and that worked. But the preference would be to use the SDK as a library and not compile the sources ourselves.

Is it an option to add the name to a different field for name? I.e. something like

`@SerializedName(value = "name")
     private String mediaItemName;`

**Comment by WouterToering** [comment]
Hey @onnovandillen,

Sorry for not getting back to you early. I've made the requested changes (see https://github.com/Bynder/bynder-java-sdk/pull/23/commits/1e46cd0a5da5907177d573c619bad3c81fa05c98) and just initiated the release of the new version (2.2.) to maven, which should be available shortly.

**Comment by onnovandillen** [comment]
Thanks @WouterToering, it is available now and solves my issue.
