### ISSUE TITLE
Java SDK - Not seeing "Original Filename" in interface

### ISSUE THREAD

**Issue by jms-jtapp** [Bynder/bynder-java-sdk#24]
Hi there,

A member of the team at my company built a custom mass uploader that has been working well for about a year. It appears to have been built on version 1.1.2 of the SDK (based on the version tag in the pom.xml).

One issue that has come up is that when assets are uploaded via this custom tool, the Original Filename field is not showing up in the "info" pane on the right-hand side of the Bynder interface when selecting an asset. It is present on assets that are uploaded thru the Bynder interface however. Also, the tile to download the original image does have the correct original filename.

Any thoughts on what may be causing this?

**Comment by TimBloembergen** [comment]
@jms-jtapp Sorry for the very late reply. The "original filename" showing on the info pane is a feature that can be enabled by support (support@bynder.com). When this feature gets enabled the original filename will be displayed.
