### ISSUE TITLE
assetService.getMediaList(mediaQuery)  Publication or Creation date

### ISSUE THREAD

**Issue by petervandepoele** [Bynder/bynder-java-sdk#25]
Hi, how can I find the asset-records created (since) yesterday?

**Comment by Arpit-Sharma-USC** [comment]
Hi @petervandepoele, we just released a new [version](https://search.maven.org/artifact/com.bynder/bynder-java-sdk/2.2.13/jar) of this sdk addressing this issue. Thanks again for reporting this!
