### ISSUE TITLE
Set an asset as limited

### ISSUE THREAD

**Issue by devaholic** [Bynder/bynder-java-sdk#33]
Hi,

Is there a way to set an asset as "limited access" when uploading a file and modifying an existen asset?

From bynder portal you can set it, also using the Rest API can be set just on editing not in upload, but I have not see anything related to limited access on the SDK.

Regards
Rabie

**Comment by Arpit-Sharma-USC** [comment]
Hi @devaholic, we just released a new [version](https://search.maven.org/artifact/com.bynder/bynder-java-sdk/2.2.13/jar) of this sdk addressing this issue. Thanks again for reporting this!
