### ISSUE TITLE
Unauthorized Response using permanent token

### ISSUE THREAD

**Issue by diegobs2** [Bynder/bynder-java-sdk#34]
Hello,

I am trying to set sdk java api for integrate with bynder using permanent token.

I use guidelines indicates [here ](https://bynder.docs.apiary.io/#reference/oauth-1.0a), for generate consumer and permanent token. 
I am doing something wrong?
How must I generate permanent token then?

I test it with Postman with Oauth 1.0 and it is working with the generated tokens.

**Comment by WouterToering** [comment]
Hi @diegobs2,

The current version of the SDK no longer includes OAuth 1.0 support but only OAuth 2.0 and the custom "Permanent Tokens", which are not part of OAuth standard. Please see the general knowledge base for explanations on how to create [Permanent Tokens](https://support.bynder.com/hc/en-us/articles/360013875300-Permanent-Tokens) or [OAuth2.0 clients](https://support.bynder.com/hc/en-us/articles/360013875180-Create-your-OAuth-Apps).

If you would still like to use OAuth1.0 you can use [SDK version 1.1.4](https://github.com/Bynder/bynder-java-sdk/tree/1.1.4), which is the last version that still supported this.

**Comment by diegobs2** [comment]
Hi,
thanks you very much, i solved It using permanet token.

Obtener Outlook para Android<https://aka.ms/ghei36>
________________________________
