### ISSUE TITLE
How to access the value associated to a propertyOption 

### ISSUE THREAD

**Issue by abhishekbhattacharyya** [Bynder/bynder-java-sdk#4]
https://github.com/Bynder/bynder-java-sdk/blob/0fd5f65747c98357036840660f2ec08fed3e389a/src/main/java/com/bynder/sdk/model/Media.java#L102
Media has a list of meta property options associated. 

How do i access the value associated with that meta property option?

Media " {
{
    "propertyOptions": [
        "270105C9-7E3A-41AB-9FB89F0B9EA3217B"
   ],
   "property_starrating": [
        "5"
    ]
}

How do i access the value property_starrating? i don't see an existing API which does this?

**Comment by danielsequeira** [comment]
There's a new API call to retrieve metaproperty options by id, this is not implemented in the SDK yet though, but feel free to add it. This is the call: http://docs.bynder.apiary.io/#reference/metaproperties/metaproperty-option-operations/retrieve-metaproperty-options

**Comment by abhishekbhattacharyya** [comment]
@danielsequeira Thanks for the Quick reply

I have tried the API you have mentioned
http://docs.bynder.apiary.io/#reference/metaproperties/metaproperty-option-operations/retrieve-metaproperty-options

The response  is 
[
    {
        "displayLabel": "Local",
        "date": "August, 29 2016 21:00:57 +0000",
        "pregeneratedZipFileSize": 0,
        "labels": {
            "en_US": "Local"
        },
        "linkedOptionIds": [],
        "isSelectable": 1,
        "zindex": 0,
        "product_suffix": "",
        "name": "local",
        "id": "270105C9-7E3A-41AB-9FB89F0B9EA3217B",
        "active": 1,
        "label": "Local",
        "descriptions": {},
        "description": "",
        "hideByDefault": 0,
        "metapropertyId": "CDCA0607-58D5-46EB-ADE922E143AAD7A0"
    }
]

I want to access the value associated to the metaproperty. Can you suggest how do i do it?
"property_starrating": [
"3"
]

![screen shot 2017-08-30 at 11 42 55 am](https://user-images.githubusercontent.com/6095365/29889280-775ab20a-8d78-11e7-96a0-5dbf646696c8.png)

**Comment by danielsequeira** [comment]
You pass the id of another metaproperty option, the id of the metaproperty option 3 (stars) from the metaproperty "starrating" is "5055FA8F-75E7-4126-812A38B83631B556". The id that you passed "270105C9-7E3A-41AB-9FB89F0B9EA3217B" belongs to the metaproperty option "local" from the metaproperty "Channel", like indicates in the response that you got.

**Comment by abhishekbhattacharyya** [comment]
Thanks was able to figure it.
