### ISSUE TITLE
Pagination Support for getMediaList

### ISSUE THREAD

**Issue by abhishekbhattacharyya** [Bynder/bynder-java-sdk#5]
The API documentation has support for pagination. 
http://docs.bynder.apiary.io/#reference/assets/asset-operations/retrieve-assets

This SDK does not support pagination information.
"count": {
        "orientation": {
            "portrait": 5,
            "landscape": 3
        },
        "total": 8
    },
Observable<Response<List<Media>>> getMediaList(MediaQuery mediaQuery);

**Comment by danielsequeira** [comment]
It supports pagination, by using the setLimit and setPage methods of the MediaQuery class. What it doesn't support is the return of count results, mainly because the json object return would be totally different. But you can easily add this, let me know if you need help with it.

**Comment by abhishekbhattacharyya** [comment]
@danielsequeira Sure. Thanks for your input
