### ISSUE TITLE
Wrong brand information returned

### ISSUE THREAD

**Issue by tmmlsBE** [Bynder/bynder-java-sdk#56]
Hi,

When trying to use the API, the wrong brand information is returned. The name does not correspond to the front-end, and it doesn't show the sub brands.

![Schermafbeelding 2021-03-11 om 11 35 00](https://user-images.githubusercontent.com/40865364/110774516-2d17c000-825e-11eb-963a-9bd213e701b7.png)

![Schermafbeelding 2021-03-11 om 11 33 43](https://user-images.githubusercontent.com/40865364/110774535-3012b080-825e-11eb-96e8-cf4d092714ec.png)

I have this issue, using the SDK, and using Postman.

How can I fix this?

Thanks

**Comment by githuib** [comment]
Hi @tmmlsBE 

Unfortunately I don't have a solution for this straight away, but I created a ticket for this issue, so we can further investigate this.

**Comment by githuib** [comment]
@tmmlsBE May I ask what API request you exactly made by the way?

**Comment by githuib** [comment]
@tmmlsBE I think there is some confusion going on here. In your screenshot, the "Brand" and "Subbrand" items are actually metaproperties that happened to be set up differently than the actual brands (and subbrands).

You could consider to use `AssetService.getMetaproperties()` instead, if that suits your use case.
