### ISSUE TITLE
How to connect using grant type "Client credentials"?

### ISSUE THREAD

**Issue by tmmlsBE** [Bynder/bynder-java-sdk#59]
Hi,

With this post I would like to ask a question.

How to connect to your Bynder account using grant type "Client credentials". The sample code file doesn't include an  example for connecting and authenticating using this grant type.

This doesn't work ...

            String clientURL = "the bynder url";
            String clientID = "the clientID";
            String clientSecret = "the client secret";

            URL url = new URL(clientURL);
            OAuthSettings oAuthSettings = new OAuthSettings(clientID, clientSecret, null);
            Configuration conf = new Configuration.Builder(url).setOAuthSettings(oAuthSettings).build();
            BynderClient client = BynderClient.Builder.create(conf);

            OAuthService oauthService = client.getOAuthService();
            List<String> scopes = Arrays.asList("offline", "asset:read", "asset:write");

            Observable<Token> token = oauthService.getAccessToken("Test", scopes);

            AssetService assetService = client.getAssetService();

            // Call the API to request for brands
            List<Brand> brands = assetService.getBrands().blockingSingle().body();
            for (Brand brand : brands) {
                System.out.println(brand.getName());
            }

An exception is thrown ...
com.bynder.sdk.exception.BynderRuntimeException: Token is not defined in Configuration

Thank you

**Comment by TimBloembergen** [comment]
Hi @tmmlsBE, the grant_type Client Credentials is not yet supported in the current version of the SDK. It will be part of our next release of our SDK(s).

**Comment by tmmlsBE** [comment]
Hi Tim,
Thanx for sharing this update. Any news on when the new version will be available?
Thanx

**Comment by TimBloembergen** [comment]
We don't have a specific date yet so it's best to keep an eye on this repo. When we do release it we will also update our api docs on https://bynder.docs.apiary.io

**Comment by TimBloembergen** [comment]
@tmmlsBE I'll close this one as the new release will include client credentials as an authentication method. It's now known yet when it will be released but keep an eye on out on this repo.
