### ISSUE TITLE
How uplod asset  with  tags 

### ISSUE THREAD

**Issue by onikraj** [Bynder/bynder-java-sdk#60]
Hello,

I am currently discovering the Java Bynder SDK.
I managed to understand the AppSample.java class and integrate the asset in Bynder.

But I need another example to load the asset with : 
* tag or tags
* Collection Name ( Collection already exist) 

Could you share an example of java code?

Thank you very much,
Best regards,
Otman

**Comment by githuib** [comment]
Hi @onikra

In case you still would like to know this, could you please clarify what you want to achieve exactly?
Do you want to upload an asset or search for assets?

**Comment by eborisowIQVIA** [comment]
For me, I am uploading an asset and then would need to add tags to the uploaded asset.

**Comment by githuib** [comment]
Unfortunately, it's currently not possible to add tags using the java SDK.

An asset can be added to collection with the following code:
```
        SaveMediaResponse saveMediaResponse = assetService.uploadFile(
                new UploadQuery("/path/to/file.ext", "some_brand_id")
        ).blockingSingle();
        client.getCollectionService().addMediaToCollection(
                new CollectionAddMediaQuery(
                        "some_collection_id",
                        new String[]{saveMediaResponse.getMediaId()}
                )
        );
```

**Comment by eborisowIQVIA** [comment]
Hi @githuib ,

Any chance we can add the 'add tags' requirement to a backlog?

Thanks,
Eric

**Comment by Arpit-Sharma-USC** [comment]
Hi @eborisowIQVIA We just released a new [version](https://search.maven.org/artifact/com.bynder/bynder-java-sdk/2.2.13/jar) of this sdk addressing this issue. Thanks again for reporting this!
