### ISSUE TITLE
Remove slf4j-simple or document default binding and how to exclude

### ISSUE THREAD

**Issue by frederikheremans** [Bynder/bynder-java-sdk#7]
The bynder SDK comes with a compile-time depencency on slf4j-simple, which contains a SLF4J binding. Since the SDK is a library intended to be included in other project, you may end up with multiple providers (See http://www.slf4j.org/codes.html#multiple_binding). It may be better to either:

1. Mark the dependency as 'test' scope and document that users need to add an appropriate binding based on their preferred logging implementation.
2. Keep the compile scope, but add a section to the readme, explaining the binding is included and add a snippet on how to exclude it - for maven this would be:
```
<dependency>
  <groupId>com.bynder</groupId>
  <artifactId>bynder-java-sdk</artifactId>
  <version>${bynder.version}</version>
  <exclusions>
    <exclusion>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-simple</artifactId>
    </exclusion>
  </exclusions>
</dependency>
```

**Comment by danielsequeira** [comment]
Thanks a lot for the tip! Already released a new version (1.0.9) with the slf4j-simple dependency scope as "test".
