### ISSUE TITLE
Missing support for required meta property option values in MediaQuery

### ISSUE THREAD

**Issue by frederikheremans** [Bynder/bynder-java-sdk#9]
1. Currently, the `MediaQuery` allows you to specify a list of property option IDs. The docs may also be clarified a bit to prevent confusion, the javadoc for the `propertyOptionIds` states:
    > Metaproperty option ids that the media asset **has to have**.

    Which is a bit contradictory to what the API-docs state:
    > This parameter searches for assets that contain at **least one** of the metaproperty options passed in the list.

2. Our usecase needs to combine the "one of" and "should have" (eg. assets which have a meta-property indicating they are part of region X OR region Y AND should be press-releases). unfortunatly, the SDK does not allow using the "must have" using the `property_METAPROPERTY_NAME` approach. Should be good to have this added to the SDK to support these usacases. 

I've added simple support for this on our fork of the SDK (see https://github.com/frederikheremans/bynder-java-sdk/commit/4490ab18c866fd26d1fe3fd27fa35d7f911cd1bd). This adds a new `ConversionType.METAPROPERTY_MAP_FIELD` which accepts a map with meta property names and a value and converts it to the correct `property_*` params in the raw request map.

WDYT? is this something you guys are willing to include. If so, I'm happy to contribute a PR for this (the current solution is enough for our usecase, but does not support multiple option values yet).

**Comment by danielsequeira** [comment]
You are totally right, the javadoc is not correct, since the correct behaviour is the one stated in the API documentation, I will fix this.

Sure, this is one of the main reasons why we open source our SDKs, so we can have more people contributing to them, since we don't always have the time to work on them or even what are the more important features for the users of our SDKs. So feel free to create that PR :)

**Comment by danielsequeira** [comment]
These changes will be in the version 1.1.2 that I just released
