### ISSUE TITLE
Can not submit multiple meta data properties value for a single key

### ISSUE THREAD

**Issue by nitin1edate** [Bynder/bynder-java-sdk#95]
hello,

We have a requirement of storing the multiple meta Data properties value for a single key.
we are using the below from SDK. We are assigning array of values for a key

<img width="523" alt="image" src="https://user-images.githubusercontent.com/118887982/203508961-aa695d7a-9696-481a-9c6c-6eeff96e747f.png">

MetaProperty = F387CEC2-CA58-4BD1-9ED8E416E3D71495 : [CE9924C7-374A-4850-A95040472A1AECE6]
MetaProperty = 9AF5E562-5F88-4034-BBE86D755CC39D53 : [61FE1B82-E3FA-4A1C-AB46B3D1C4BFC98F]
**MetaProperty = 80CFEEF1-E878-458B-91E45F934F6CE890 : [1459B435-594C-4CDA-8EF8DC7FB60F1DF7, 1361F1CD-BF66-4E54-A4211A1A617C06F3]**

we are getting the exception as,

java.lang.RuntimeException: com.bynder.sdk.exception.HttpResponseException: Response{protocol=h2, code=400, message=, url=https://bakerhughessandbox.getbynder.com/api/v4/upload/poll/?items=1CF5AB27-7FC9-4BE9-9A0EA31285C3C7BB/}
{"message":"Invalid import ID","statuscode":"400"}

Can you help us to resolve this?

**Comment by TimBloembergen** [comment]
Hi Nitin,

While the error that you receive doesn't really have to do anything with the Save call (the endpoint where you can set metaproperties on asset during upload), it could perhaps be related on how you're trying to set that metaproperties with options.

I've had a look and the way you're sending the metaproperties on the save call is incorrect, you're sending an array while a String is expected. You can refer to our docs on how the parameter needs to be used in the upload query.

What needs to be send is a string value. metaproperty.00000000-0000-0000-0000000000000000 = 00000000-0000-0000-0000000000000000,00000000-0000-0000-0000000000000000

When you need to set multiple values for the same metaproperty, you'll need to send those optionid's comma seperated. If you do it that way and the Metaproperty type allows for multiple values, you'll be able to set them via that way.

Let me know if this helps.

**Comment by nitin1edate** [comment]
Thanks for this. The issue is resolved.

regards,

Nitin Edate
