### ISSUE TITLE
Not able to get new SDK 2.2.16 using maven

### ISSUE THREAD

**Issue by nitin1edate** [Bynder/bynder-java-sdk#97]
hello team,

I am not able to take SDK2.2.16 using maven. I am getting error as,

<img width="274" alt="image" src="https://user-images.githubusercontent.com/118887982/203792205-0aa17fa5-026e-4025-9bea-9c367deebe77.png">

regards,

Nitin Edate

**Comment by nitin1edate** [comment]
for the above issue, we are using following dependency

<img width="302" alt="image" src="https://user-images.githubusercontent.com/118887982/203792557-56faf818-d5f0-455b-a1d4-c2a8826bde26.png">


Nitin Edate

**Comment by Arpit-Sharma-USC** [comment]
Hi @nitin1edate, this hasn't reflected yet on the central maven repo. Once it does you'll be able to inject it into your application. Please keep track of [this](https://search.maven.org/artifact/com.bynder/bynder-java-sdk), when it shows the latest release(2.2.16) you'll be able to use it.

**Comment by Arpit-Sharma-USC** [comment]
@nitin1edate Looks like you need to clean and recompile your dependencies in the application. I was able to pull v2.2.16 in a test-application and successfully upload with a custom name. 

If you are using intelliJ this(https://stackoverflow.com/questions/9980869/force-intellij-idea-to-reread-all-maven-dependencies#:~:text=Press%20Ctrl%20%2B%20Shift%20%2B%20A%20to,%E2%8C%98%20%2B%20%E2%87%A7%20%2B%20A%20instead.) is a useful thread to follow on how to reload all maven dependencies.
<img width="815" alt="Screenshot 2022-11-24 at 14 52 18" src="https://user-images.githubusercontent.com/32858287/203804148-3f4986f6-7094-4b86-b567-bed92e89554d.png">
<img width="706" alt="Screenshot 2022-11-24 at 14 52 25" src="https://user-images.githubusercontent.com/32858287/203804155-c42260ac-09b9-4ba7-9195-fca2e7927797.png">

<img width="1440" alt="Screenshot 2022-11-24 at 14 52 58" src="https://user-images.githubusercontent.com/32858287/203804807-7d6722ef-c4a8-4202-a3ad-6e9bef924e72.png">

**Comment by Arpit-Sharma-USC** [comment]
Hi @nitin1edate, is this fixed now or are you still facing issues with this?
